server:
  port: 8080

spring:
  application:
    name: ai-cs-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: aics
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: aics
        group: DEFAULT_GROUP
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

logging:
  level:
    com.aics.gateway: debug
    org.springframework.cloud.gateway: info
